# Generated by Gemini-1.5 Flash
from pytube import YouTube
from pydub import AudioSegment
import os

def youtube_to_mp3(youtube_urls, output_dir="mp3_downloads"):
    """Downloads YouTube videos and converts them to MP3."""

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    for url in youtube_urls:
        try:
            yt = YouTube(url)
            video_stream = yt.streams.filter(only_audio=True).first()

            if video_stream is None:
                print(f"No suitable audio stream found for {url}")
                continue

            filename = yt.title + ".mp4"  #Download as mp4 first
            filepath = os.path.join(output_dir, filename)
            print(f"Downloading: {yt.title}")
            video_stream.download(output_path=output_dir, filename=filename)


            #Convert to mp3 using pydub.  This part requires ffmpeg to be installed and in your system's PATH.

            audio = AudioSegment.from_file(filepath, format="mp4") # Or another suitable format if needed.
            mp3_filename = yt.title + ".mp3"
            mp3_filepath = os.path.join(output_dir, mp3_filename)
            audio.export(mp3_filepath, format="mp3")
            os.remove(filepath) #remove the temporary mp4 file
            print(f"Converted to MP3: {mp3_filename}")

        except Exception as e:
            print(f"Error processing {url}: {e}")



if __name__ == "__main__":
    youtube_urls = [
        "YOUR_YOUTUBE_URL_1",
        "YOUR_YOUTUBE_URL_2",
        # Add more URLs here
    ]
    youtube_to_mp3(youtube_urls)
